platform :ios, '8.0'
use_frameworks!

target 'ClothesStore' do
  # Pods for ClothesStore
  pod 'ObjectMapper', '~> 2.2'

  target 'ClothesStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClothesStoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
